### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by ddlddl58** [pankajkarman/HyTraj#1]
Hi pankajkarman,

     The package is very useful in analysing potiential source.
     I see the calculation of pscf/cwt/rtwc, it does not consider the trajtory point height, all is in 2D surface.
     But in working directory, there is a terrain file, I think if the calculation can take the height into consideration,ie in a 3D space, it will be more excellent.

Regards,

ddlddl58

**Comment by pankajkarman** [comment]
Hello ddlddl58,
Thank you very much for this very useful suggestion. I am adding this one to plans for future feature addition.
